import { ROLES } from "./roles";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {

  // =========================
  // 👑 ADMIN (FULL SYSTEM ACCESS)
  // =========================
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,

    // users & roles
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.ASSIGN_ROLE_TO_USER,
    PERMISSIONS.VIEW_ROLE_DETAIL,
    PERMISSIONS.UPDATE_ROLE_PERMISSIONS,

    // standard
    PERMISSIONS.MANAGE_STANDARD,
    PERMISSIONS.VIEW_STANDARD_DETAIL,
    PERMISSIONS.UPDATE_STANDARD,
    PERMISSIONS.IMPORT_EVIDENCE_CATEGORY,

    // assignment
    PERMISSIONS.MANAGE_ASSIGNMENT,
    PERMISSIONS.VIEW_MY_ASSIGNMENTS,
    PERMISSIONS.TAKE_ASSIGNMENT,
    PERMISSIONS.UPDATE_ASSIGNMENT_STATUS,

    // evidence full control
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.UPLOAD_EVIDENCE,
    PERMISSIONS.SUBMIT_EVIDENCE,
    PERMISSIONS.RESUBMIT_EVIDENCE,
    PERMISSIONS.RECALL_EVIDENCE,
    PERMISSIONS.REVIEW_EVIDENCE,
    PERMISSIONS.APPROVE_EVIDENCE,
    PERMISSIONS.REJECT_EVIDENCE,
    PERMISSIONS.COMMENT_EVIDENCE,
    PERMISSIONS.WAIT_REVIEW_EVIDENCE,
    PERMISSIONS.RECEIVE_FEEDBACK_EVIDENCE,

    // improvement
    PERMISSIONS.MANAGE_IMPROVEMENT,

    // reports
    PERMISSIONS.VIEW_REPORT,
    PERMISSIONS.VIEW_STATISTICS,
    PERMISSIONS.EXPORT_REPORT,
    PERMISSIONS.FILTER_REPORT,
  ],

  // =========================
  // 🟡 QA (KT & ĐBCL)
  // =========================
  [ROLES.QA]: [
    PERMISSIONS.VIEW_DASHBOARD,

    PERMISSIONS.MANAGE_STANDARD,
    PERMISSIONS.VIEW_STANDARD_DETAIL,
    PERMISSIONS.UPDATE_STANDARD,
    PERMISSIONS.IMPORT_EVIDENCE_CATEGORY,

    PERMISSIONS.MANAGE_ASSIGNMENT,
    PERMISSIONS.VIEW_MY_ASSIGNMENTS,

    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.APPROVE_EVIDENCE,
    PERMISSIONS.REJECT_EVIDENCE,
    PERMISSIONS.UPLOAD_EVIDENCE,
    PERMISSIONS.REVIEW_EVIDENCE,
    PERMISSIONS.COMMENT_EVIDENCE,

    PERMISSIONS.VIEW_REPORT,
    PERMISSIONS.VIEW_STATISTICS,
  ],

  // =========================
  // 🟢 FACULTY (ĐƠN VỊ / KHOA)
  // =========================
  [ROLES.FACULTY]: [
    PERMISSIONS.VIEW_DASHBOARD,

    PERMISSIONS.VIEW_MY_ASSIGNMENTS,
    PERMISSIONS.TAKE_ASSIGNMENT,

    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.UPLOAD_EVIDENCE,

    PERMISSIONS.SUBMIT_EVIDENCE,
    PERMISSIONS.RESUBMIT_EVIDENCE,
    PERMISSIONS.RECALL_EVIDENCE,

    PERMISSIONS.WAIT_REVIEW_EVIDENCE,
    PERMISSIONS.RECEIVE_FEEDBACK_EVIDENCE,

    PERMISSIONS.COMMENT_EVIDENCE,
  ],

  // =========================
  // 🔵 MANAGER (TRƯỞNG PHÒNG)
  // =========================
  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.REVIEW_EVIDENCE,
    PERMISSIONS.APPROVE_EVIDENCE,
    PERMISSIONS.REJECT_EVIDENCE,
    PERMISSIONS.COMMENT_EVIDENCE,

    PERMISSIONS.MANAGE_IMPROVEMENT,

    PERMISSIONS.VIEW_REPORT,
    PERMISSIONS.VIEW_STATISTICS,
  ],

  // =========================
  // 🟣 LEADER
  // =========================
  [ROLES.LEADER]: [
  PERMISSIONS.VIEW_DASHBOARD,

  PERMISSIONS.VIEW_EVIDENCE,

  PERMISSIONS.REVIEW_EVIDENCE,
  PERMISSIONS.APPROVE_EVIDENCE,
  PERMISSIONS.REJECT_EVIDENCE,

  PERMISSIONS.COMMENT_EVIDENCE,

  PERMISSIONS.VIEW_REPORT,
  PERMISSIONS.VIEW_STATISTICS,
],
};