import { ROLES } from "./roles";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {

  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.QA]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.STANDARD_MANAGE,
    PERMISSIONS.STANDARD_VIEW,
    PERMISSIONS.STANDARD_UPDATE,
    PERMISSIONS.STANDARD_IMPORT,

    PERMISSIONS.ASSIGNMENT_MANAGE,
    PERMISSIONS.ASSIGNMENT_VIEW_MY,

    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_REVIEW,
    PERMISSIONS.EVIDENCE_APPROVE,
    PERMISSIONS.EVIDENCE_REJECT,
    PERMISSIONS.EVIDENCE_COMMENT,
    PERMISSIONS.EVIDENCE_UPLOAD,

    PERMISSIONS.REPORT_VIEW,
  ],

  [ROLES.FACULTY]: [
    PERMISSIONS.ASSIGNMENT_VIEW_MY,
    PERMISSIONS.ASSIGNMENT_TAKE,

    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_UPLOAD,
    PERMISSIONS.EVIDENCE_SUBMIT,
    PERMISSIONS.EVIDENCE_COMMENT,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_REVIEW,
    PERMISSIONS.EVIDENCE_APPROVE,
    PERMISSIONS.EVIDENCE_REJECT,
    PERMISSIONS.EVIDENCE_COMMENT,
    PERMISSIONS.IMPROVEMENT_MANAGE,
    PERMISSIONS.REPORT_VIEW,
  ],

  [ROLES.LEADER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.EVIDENCE_REVIEW,
    PERMISSIONS.EVIDENCE_APPROVE,
    PERMISSIONS.REPORT_VIEW,
  ],
};