import { ROLES } from "./roles";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {

  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_STANDARD,
    PERMISSIONS.IMPORT_EVIDENCE_CATEGORY,
    PERMISSIONS.MANAGE_EVALUATION,
    PERMISSIONS.MANAGE_ASSIGNMENT,
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.UPLOAD_EVIDENCE,
    PERMISSIONS.REVIEW_EVIDENCE,
    PERMISSIONS.MANAGE_IMPROVEMENT,
    PERMISSIONS.VIEW_REPORT,
  ],

  [ROLES.QA]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_STANDARD,
    PERMISSIONS.IMPORT_EVIDENCE_CATEGORY,
    PERMISSIONS.MANAGE_EVALUATION,
    PERMISSIONS.MANAGE_ASSIGNMENT,
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.UPLOAD_EVIDENCE,
    PERMISSIONS.REVIEW_EVIDENCE,
    PERMISSIONS.MANAGE_IMPROVEMENT,
    PERMISSIONS.VIEW_REPORT,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_EVALUATION,
    PERMISSIONS.REVIEW_EVIDENCE,
    PERMISSIONS.MANAGE_IMPROVEMENT,
    PERMISSIONS.VIEW_REPORT,
  ],

  [ROLES.FACULTY]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_EVIDENCE,
    PERMISSIONS.UPLOAD_EVIDENCE,
  ],

  [ROLES.LEADER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_REPORT,
  ],
};